# Generated by Django 6.0.1 on 2026-01-26 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='Unikalny numer seryjny certyfikatu X.509.', max_length=128, unique=True)),
                ('fingerprint_sha256', models.CharField(help_text='Odcisk palca certyfikatu w SHA-256.', max_length=64, unique=True)),
                ('subject_dn', models.TextField(help_text='Distinguished Name (DN) właściciela certyfikatu.')),
                ('issuer_dn', models.TextField(help_text='Distinguished Name (DN) wystawcy certyfikatu.')),
                ('not_before', models.DateTimeField(help_text='Data i czas rozpoczęcia ważności certyfikatu.')),
                ('not_after', models.DateTimeField(db_index=True, help_text='Data i czas zakończenia ważności certyfikatu.')),
                ('public_key_algorithm', models.CharField(help_text='Algorytm klucza publicznego.', max_length=50)),
                ('signature_algorithm', models.CharField(help_text='Algorytm podpisu certyfikatu.', max_length=100)),
                ('key_size', models.IntegerField(help_text='Długość klucza w bitach.')),
                ('encrypted_private_key', models.TextField(help_text='Zaszyfrowany klucz prywatny w formacie PEM.', null=True)),
                ('public_key', models.TextField(help_text='Klucz publiczny w formacie PEM.')),
                ('is_ca', models.BooleanField(db_index=True, default=False, help_text='Określa, czy certyfikat jest certyfikatem CA.')),
                ('key_usage', models.TextField(blank=True, help_text='Rozszerzenie Key Usage certyfikatu.')),
                ('extended_key_usage', models.TextField(blank=True, help_text='Rozszerzenie Extended Key Usage certyfikatu.')),
                ('pem_data', models.TextField(help_text='Certyfikat zapisany w formacie PEM.')),
                ('revoked', models.BooleanField(db_index=True, default=False, help_text='Określa, czy certyfikat został unieważniony.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_sha256', models.CharField(help_text='Odcisk palca CSR (SHA-256).', max_length=64, unique=True)),
                ('subject_dn', models.TextField(help_text='Distinguished Name (DN) podmiotu żądającego certyfikatu.')),
                ('public_key', models.TextField(help_text='Klucz publiczny w formacie PEM.')),
                ('encrypted_private_key', models.TextField(help_text='Zaszyfrowany klucz prywatny powiązany z kluczem publicznym w formacie PEM.', null=True)),
                ('public_key_algorithm', models.CharField(help_text='Algorytm klucza publicznego (np. RSA, EC).', max_length=50)),
                ('key_size', models.IntegerField(help_text='Długość klucza publicznego w bitach.')),
                ('signature_algorithm', models.CharField(help_text='Algorytm podpisu CSR.', max_length=100)),
                ('csr_pem', models.TextField(help_text='Żądanie certyfikatu (CSR) w formacie PEM.')),
                ('status', models.CharField(choices=[('pending', 'Oczekujące'), ('approved', 'Zatwierdzone'), ('rejected', 'Odrzucone')], db_index=True, default='pending', help_text='Status przetwarzania CSR.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data utworzenia żądania certyfikatu.')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Data przetworzenia żądania certyfikatu.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_dn', models.TextField(help_text='Distinguished Name (DN) urzędu certyfikacji, który wystawił CRL.')),
                ('this_update', models.DateTimeField(default=django.utils.timezone.now, help_text='Data i czas wygenerowania CRL.')),
                ('next_update', models.DateTimeField(help_text='Data i czas następnej aktualizacji CRL.')),
                ('version', models.IntegerField(default=2, help_text='Wersja CRL (zwykle 1 lub 2).')),
                ('revoked_certificates', models.JSONField(blank=True, default=list, help_text='Lista unieważnionych certyfikatów (numery seryjne).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crl_pem', models.TextField(help_text='CRL (Certificate Revocation List) w formacie PEM, wygenerowany i podpisany przez CA.')),
            ],
        ),
    ]
