# Generated by Django 6.0.1 on 2026-08-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PyMitiveCA", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cert",
            name="pop_encrypted_cert_b64",
            field=models.TextField(
                blank=True,
                help_text="Certyfikat PEM zaszyfrowany AES-256-GCM (base64), do czasu potwierdzenia POP.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cert",
            name="pop_kem_ciphertext_b64",
            field=models.TextField(
                blank=True,
                help_text="Szyfrogram KEM (base64) potrzebny do odtworzenia sekretu przy potwierdzeniu POP.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cert",
            name="pop_nonce_b64",
            field=models.TextField(
                blank=True,
                help_text="Nonce AES-GCM (base64) użyty do zaszyfrowania certyfikatu.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cert",
            name="pop_pending",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Certyfikat wystawiony dla klucza KEM (np. ML-KEM) oczekuje na potwierdzenie posiadania klucza (POP) - pem_data jest puste, dopóki żądający nie odszyfruje pop_encrypted_cert i nie potwierdzi tego przez confirm_cert/.",
            ),
        ),
        migrations.AlterField(
            model_name="cert",
            name="pem_data",
            field=models.TextField(
                blank=True,
                help_text="Certyfikat zapisany w formacie PEM. Puste, dopóki pop_pending=True.",
            ),
        ),
    ]
