# Generated by Django 6.0.1 on 2026-08-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PyMitiveCA", "0002_cert_pop_encrypted_cert_b64_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cert",
            name="key_size",
            field=models.IntegerField(
                blank=True,
                help_text="Długość klucza w bitach (puste dla algorytmów bez tego pojęcia, np. ECDSA/ED25519 - krzywa jest wtedy zakodowana w public_key_algorithm).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="certrequest",
            name="key_size",
            field=models.IntegerField(
                blank=True,
                help_text="Długość klucza publicznego w bitach (puste dla algorytmów bez tego pojęcia, np. ECDSA/ED25519 - krzywa jest wtedy zakodowana w public_key_algorithm).",
                null=True,
            ),
        ),
    ]
