# Generated by Django 6.0.1 on 2026-08-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PyMitiveCA", "0003_alter_cert_key_size_alter_certrequest_key_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="cert",
            name="revoked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data i czas unieważnienia certyfikatu. Wymagana przez OCSP (revocationTime, RFC 6960) i przez wpisy w CRL - puste, dopóki certyfikat nie został unieważniony.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cert",
            name="key_size",
            field=models.IntegerField(
                blank=True,
                help_text="Długość klucza: liczba bitów dla RSA (moduł), ECDSA (rząd krzywej) i ED25519 (255), albo numer wariantu dla ML-KEM (768/1024).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="certrequest",
            name="key_size",
            field=models.IntegerField(
                blank=True,
                help_text="Długość klucza publicznego: liczba bitów dla RSA (moduł), ECDSA (rząd krzywej) i ED25519 (255), albo numer wariantu dla ML-KEM (768/1024).",
                null=True,
            ),
        ),
    ]
