# Generated by Django 6.0.1 on 2026-08-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PyMitiveCA", "0004_cert_revoked_at_alter_cert_key_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cert",
            name="revocation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unspecified", "Nieokreślony"),
                    ("key_compromise", "Kompromitacja klucza podmiotu"),
                    ("ca_compromise", "Kompromitacja klucza CA"),
                    ("affiliation_changed", "Zmiana powiązania podmiotu"),
                    ("superseded", "Zastąpiony nowym certyfikatem"),
                    ("cessation_of_operation", "Zaprzestanie działalności"),
                    ("certificate_hold", "Tymczasowe zawieszenie"),
                    ("privilege_withdrawn", "Cofnięcie uprawnień"),
                    ("aa_compromise", "Kompromitacja Attribute Authority"),
                ],
                help_text="Powód unieważnienia (RFC 5280 CRLReason) - puste, dopóki certyfikat nie został unieważniony.",
                max_length=30,
                null=True,
            ),
        ),
    ]
